name: shirahsoft_muslim
description: "زاد المسلم - تطبيق قرآني شامل يوفر قراءة القرآن الكريم، الأحاديث النبوية، مواقيت الصلاة، القبلة، التفسير، والأذكار بتصميم حديث ومعمارية نظيفة"

publish_to: "none"

version: 1.1.0+6

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_localizations: # to add a lot of languages
    sdk: flutter
  flex_color_scheme: ^8.3.0 # to make custom theme
  flutter_riverpod: ^3.3.1 # to handle state
  isar_community: ^3.3.2 # database
  isar_community_flutter_libs: ^3.3.2 # database ext
  intl: ^0.20.2 # to make multi language app
  path_provider: ^2.1.5 # to get paths of device
  flutter_svg: ^2.2.2
  shared_preferences: ^2.5.3
  logger: ^2.6.2
  flutter_screenutil: ^5.9.3
  dio: ^5.9.1
  geolocator: ^14.0.2 # to get user location for pray times and qepla
  adhan: ^2.0.0+1
  riverpod_annotation: ^4.0.2
  geocoding: ^4.0.0
  flutter_local_notifications: ^22.0.1
  timezone: ^0.11.0
  get_it: ^9.2.1
  dartz: ^0.10.1
  equatable: ^2.0.8
  internet_connection_checker_plus: ^3.1.0
  connectivity_plus: ^7.0.0
  qcf_quran: ^0.0.5
  flutter_staggered_animations: ^1.1.1
  share_plus: ^13.1.0
  just_audio: ^0.10.5
  just_audio_background: ^0.0.1-beta.12
  audio_video_progress_bar: ^2.0.3
  rxdart: ^0.28.0
  wakelock_plus: ^1.5.1
  skeletonizer: ^2.1.3
  flutter_compass: ^0.8.1
  lat_lng_to_timezone: ^0.2.0
  flutter_markdown: ^0.7.7+1
  webview_flutter: ^4.13.1
  scrollable_positioned_list: ^0.3.8
  flutter_staggered_grid_view: ^0.7.0
  flutter_timezone: ^5.0.2
  hijri: ^3.0.0
  url_launcher: ^6.3.2
  html: ^0.15.6
  permission_handler: ^12.0.3
  flutter_native_splash: ^2.4.8
  bot_toast: ^4.1.3
  firebase_core: ^4.12.1
  firebase_remote_config: ^6.5.5
  package_info_plus: ^10.2.1
  in_app_update: ^5.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.4.6
  isar_community_generator: ^3.3.2
  riverpod_generator: ^4.0.3
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/json/
    - assets/images/
    - assets/icons/
    - assets/sounds/

  fonts:
    - family: Amiri
      fonts:
        - asset: assets/fonts/Amiri/Amiri-Regular.ttf
        - asset: assets/fonts/Amiri/Amiri-Italic.ttf
          style: italic
        - asset: assets/fonts/Amiri/Amiri-Bold.ttf
          weight: 700
        - asset: assets/fonts/Amiri/Amiri-BoldItalic.ttf
          weight: 700
          style: italic
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo/Cairo-Light.ttf
          weight: 300
        - asset: assets/fonts/Cairo/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cairo/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Cairo/Cairo-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Cairo/Cairo-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Cairo/Cairo-Black.ttf
          weight: 900
    - family: "Tajawal"
      fonts:
        - asset: assets/fonts/Tajawal/Tajawal-Regular.ttf
        - asset: assets/fonts/Tajawal/Tajawal-Light.ttf
          weight: 300
        - asset: assets/fonts/Tajawal/Tajawal-Medium.ttf
          weight: 500
        - asset: assets/fonts/Tajawal/Tajawal-Bold.ttf
          weight: 700
        - asset: assets/fonts/Tajawal/Tajawal-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Tajawal/Tajawal-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Tajawal/Tajawal-Black.ttf
          weight: 900
    - family: "Quran"
      fonts:
        - asset: assets/fonts/quran_font/uthmanic_hafs_v20.ttf
    - family: "Naskh"
      fonts:
        - asset: assets\fonts\naskh\UthmanTN_v2-0.ttf

flutter_native_splash:
  color: "#137481"
  image: assets/images/ic_launcher_foreground.png
  image_android: "assets/images/ic_launcher_foreground.png"
  fullscreen: true

  android_12:
    color: "#007487"
    image: assets/images/ic_launcher_foreground.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true

  image_path: "assets/images/app_icon.png"

  adaptive_icon_background: "#007487"
  adaptive_icon_foreground: "assets/images/ic_launcher_foreground.png"
  adaptive_icon_foreground_inset: 0

  min_sdk_android: 21
